# Generated by Django 5.2.4 on 2025-07-17 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERADOR', 'Operador')], default='OPERADOR', max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='core.faena')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('FINALIZADA', 'Finalizada')], default='INICIADA', max_length=20)),
                ('foto_inicio', models.ImageField(blank=True, null=True, upload_to='fotos_tareas/')),
                ('foto_fin', models.ImageField(blank=True, null=True, upload_to='fotos_tareas/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('faena', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faena')),
                ('herramientas', models.ManyToManyField(to='core.herramienta')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_operador', to=settings.AUTH_USER_MODEL)),
                ('personas_involucradas', models.ManyToManyField(related_name='tareas_involucrado', to=settings.AUTH_USER_MODEL)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion')),
                ('vehiculos', models.ManyToManyField(to='core.vehiculo')),
            ],
        ),
    ]
