# Generated by Django 5.2.4 on 2025-07-18 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_faena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='faena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena'),
        ),
    ]
