# Generated by Django 5.2.4 on 2025-07-18 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_perfil_faena'),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='faena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='faena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faena'),
        ),
    ]
